# File: .github/workflows/ci-cd.yml
name: Build, Test & Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish artifacts
        run: dotnet publish -c Release -o publish

      - name: Azure CLI login  # DEMO ONLY: hard-coded creds
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "VulnerableEcomLab-SP-ClientID",
              "clientSecret": "VulnerableEcomLab-SP-Secret",
              "subscriptionId": "12345678-90ab-cdef-1234-567890abcdef",
              "tenantId": "abcdef12-3456-7890-abcd-ef1234567890"
            }

      - name: Deploy to Azure Web App  # DEMO ONLY: hard-coded names
        run: |
          az webapp deploy \
            --resource-group "VulnerableECommerceLabRG" \
            --name "VulnerableECommerceLabApp" \
            --src-path publish
