# File: .github/workflows/dotnet.yml
# Purpose: Build, test, and deploy VulnerableECommerceMVC via GitHub Actions
# WARNING: Uses hard-coded credentials and app names for demo only.
#          In production, store all sensitive values in GitHub Secrets.

name: Build-Test-Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install .NET 7 SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # 3) Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # 4) Build the solution
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5) Run unit tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # 6) Publish the app to a folder
      - name: Publish
        run: dotnet publish --configuration Release --output publish


